# Generated by Django 3.0.2 on 2020-04-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200402_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download_Links',
        ),
        migrations.AlterField(
            model_name='movie_links',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=1),
        ),
    ]
